name: Update latest.json
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Make directory
        run: mkdir publish

      - name: Generate latest.json file
        run: |
          wget https://api.github.com/repos/${{ github.repository }}/releases/latest -O publish/latest.json
          wget https://api.github.com/repos/himesamanoyume/Auto_Simulated_Universe/releases/latest -O publish/universe-latest.json

      - name: Purge jsdelivr CDN
        run: |
          cd publish || exit 1
          curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/latest.json"
          curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/fight-latest.json"
          curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/universe-latest.json"
